### ISSUE TITLE
Proposal: Rename to bibtex-capf

### ISSUE THREAD

**Issue by minad** [mclear-tools/bibtex-capf#1]
* This naming scheme is common on MELPA.
* The name bibtex-capf makes a bit more sense "bibtex completion at point function".
* Most packages use the naming scheme "x-completion-at-point" or "x-capf" for their Capfs, e.g., "dabbrev-capf" and "python-completion-at-point".

**Comment by mclearc** [comment]
@minad yeah all fair points. I had considered it, but since the inspiration was `company-bibtex` I went along with that scheme as a contrast. I also have no plans to put this on MELPA. But I'll think about it.

**Comment by minad** [comment]
I suspected that you took the name from company-bibtex. Anyway this only matters if you publish the package on MELPA/ELPA, given that the x-capf naming convention already exists there.

**Comment by mclearc** [comment]
Just FYI - I have had requests to put this on MELPA and when I do I'll be sure to fix the naming scheme.
